#!/usr/bin/env sh
# based on http://stackoverflow.com/a/3464399/1383268
HOOK_NAMES="pre-commit"
# assuming the script is in a bin directory, one level into the repo
HOOK_DIR=$(git rev-parse --show-toplevel)/.git/hooks
LOCAL_DIR=$(git rev-parse --show-toplevel)/hooks/

for hook in $HOOK_NAMES; do
    # If the hook already exists, is a file, and is not a symlink
    if [ ! -h $HOOK_DIR/$hook -a -f $HOOK_DIR/$hook ]; then
        mv $HOOK_DIR/$hook $HOOK_DIR/$hook.local
    fi
    # create the symlink, overwriting the file if it exists
    # probably the only way this would happen is if you're using an old version of git
    # -- back when the sample hooks were not executable, instead of being named ____.sample
    ln -s -f $LOCAL_DIR/hooks-wrapper $HOOK_DIR/$hook
done
